# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  packer:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-18.04]
        experimental: [false]
        include:
          - os: ubuntu-last
            experimental: true

    steps:
      -
        name: Runner info
        run: |
          sudo apt-get install -y hwinfo
          sudo hwinfo --short
          sudo mount

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install qemu-system
        run: |
          sudo apt-get update
          sudo apt-get install jq $(apt-cache search qemu | grep -E '^qemu' | cut -d ' ' -f1 | tr '\r\n' ' ' )

      # https://github.com/hashicorp/packer/issues/10892
      - name: fix qemu-system-x86_64 link
        run: |
          hash qemu-kvm
          hash qemu-system-x86_64
          hash qemu-system-i386
          hash
          ln -s /usr/libexec/qemu-kvm /usr/local/bin/qemu-system-x86_64
          ||:

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: "*.json"
          
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          #target: packer.pkr.hcl
          target: "*.json"

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          #target: packer.pkr.hcl
          target: "*.json"
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
