# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  packer:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-10.15, ubuntu-latest, ubuntu-18.04]
        experimental: [false]
        include:
          - os: ubuntu-latest
            experimental: true

    steps:
      -
        name: Runner info
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y hwinfo
          sudo hwinfo --short
          sudo mount

      - name: Runner info / find . -ls
        if: runner.os == 'Linux'
        run: |
          find . -type f -name "*" -ls

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install qemu-system
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install jq $(apt-cache search qemu | grep -E '^qemu' | grep -v -E 'qemu-system-x86-xen|qemu-user-binfmt' | cut -d ' ' -f1 | tr '\r\n' ' ' )
                                    
      # https://github.com/hashicorp/packer/issues/10892
      - name: fix qemu-system-x86_64 link
        continue-on-error: true
        run: |
          echo $PATH
          hash qemu-kvm ||:
          hash qemu-system-x86_64 ||:
          hash qemu-system-i386 ||:
          hash ||:
          df -ha ||:
          #find / -xdev -type f -name "qemu*" -ls ||:
          find ${PATH//:/\/ } -type f -name "qemu*" -ls
          ln -s --verbose /usr/libexec/qemu-kvm /usr/local/bin/qemu-system-x86_64 ||:
          ln -s --verbose /usr/bin/qemu-system-x86_64 /usr/local/bin/qemu-system-x86_64 ||:
          sudo ln -s -v /usr/local/bin/qemu* /bin ||:
          sudo ln -s -v /usr/bin/qemu* /bin ||:
          #ls -la /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
          #find / -xdev -type f -name "qemu*" -ls ||:
          echo $PATH
          find ${PATH//:/\/ } -type f -name "qemu*" -ls

      # fix backwards incompatibilities in template
      - name: Fix Template | hashicorp/packer-github-actions
        if: runner.os == 'Linux'
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: "*.json"
          
      # validate templates
      - name: Validate Template | hashicorp/packer-github-actions
        if: runner.os == 'Linux'
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          #target: packer.pkr.hcl
          target: "*.json"

      # build artifact
      - name: Build Artifact | on OS level
        #if: runner.os == 'Linux'
        #uses: hashicorp/packer-github-actions@master
        run: |
          cd ${GITHUB_WORKSPACE} || find . -type f -name "*" -ls
          export PACKER_LOG=1
          packer build -debug -parallel-builds=1 -color=false -on-error=abort "*.json"
          #target: packer.pkr.hcl

      # build artifact
      - name: Build Artifact | hashicorp/packer-github-actions
        if: runner.os == 'Linux'
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-debug -color=false -on-error=abort"
          #target: packer.pkr.hcl
          target: "*.json"
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
