# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install qemu-system
        run: |
          sudo apt-get update
          sudo apt-get install jq qemu-system qemu qemu-kvm qemu-system-data qemu-system-misc qemu-system-x86-64 qemu-system-x86 qemu-system-i386

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: "*.json"
          
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          #target: packer.pkr.hcl
          target: "*.json"

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          #target: packer.pkr.hcl
          target: "*.json"
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts
